### ISSUE TITLE
Invalid C# repositories

### ISSUE THREAD

**Issue by Aerion** [mshibanami/GitHubTrendingRSS#1]
The [C# trending repositories](https://mshibanami.github.io/GitHubTrendingRSS/daily/c#.xml) return the same content as [C trending repositories](https://mshibanami.github.io/GitHubTrendingRSS/daily/c.xml). I didn't find the C# trending repository link (or the correct data) in the provided feeds.

_Thank you for this tool._

**Comment by mshibanami** [comment]
Hi @aerion, sorry for any inconvenience. (I didn't notice your comment until now...)

Not only that bug, I was fixing some other bugs and adding more information to each feed for the past week. So now I've solved all of them, I think.
Please check and enjoy new feeds.

*Thank you for using this tool.*

**Comment by Aerion** [comment]
Perfect, thanks.
