### ISSUE TITLE
More useful title

### ISSUE THREAD

**Issue by lodenrogue** [mshibanami/GitHubTrendingRSS#10]
Great job on this project! 

I feel like the title could be a little bit more descriptive. For example, instead of just displaying the repository name it could also include the first n characters of the description. That way I don't have to open it in my RSS reader just to see if I'm interested in knowing more.

**Comment by mshibanami** [comment]
Hey @lodenrogue, sorry I missed this issue. And thanks for your feature request.

I think whether this feature would be useful or not depends on which RSS reader our users use.

Inoreader, for example, provides 5 styles (List, Expanded, Column, Card and Magazine view) and Column view doesn't show the description on each item so the descriptive title may be helpful.:

![Screen Shot 2021-04-19 at 7 23 53 pm](https://user-images.githubusercontent.com/1333214/115214203-a223c280-a145-11eb-8298-52ff8d222326.PNG)

However, other 4 styles shows the description. For instance, List view shows items like this:
![Screen Shot 2021-04-19 at 7 34 11 pm](https://user-images.githubusercontent.com/1333214/115214981-66d5c380-a146-11eb-9110-96a660f122db.PNG)

As you can see, they are different font weight and they look pretty good to me but the descriptive title would ruin that advantage.

So, for now, I leave the current implementation. Sorry. Maybe it's time that you host your own GitHubTrendingRSS. No irony, It's actually super easy to host as README describes. Please feel free to ask me if you get any troubles.

**Comment by lodenrogue** [comment]
Thanks for getting back. That's what I ended up doing: hosting my own.
