### ISSUE TITLE
is not reachable from mobile

### ISSUE THREAD

**Issue by eleblebici** [mshibanami/GitHubTrendingRSS#12]
I'm taking 404 page not found when I try to connect that address from mobile.

https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml

**Comment by mshibanami** [comment]
@eleblebici It's just hosted with GitHub Pages and I've confirmed it's not 404 so I think it's an issue of your network connection or a browser issue or some environment problems. 

Please check VPN settings or try different browsers. At least I don't really think I can do resolve your issue.
