### ISSUE TITLE
Duplicate Website Sections

### ISSUE THREAD

**Issue by HelionSmoker** [mshibanami/GitHubTrendingRSS#15]
On the [website](https://mshibanami.github.io/GitHubTrendingRSS/), there are two duplicate sections, that point to the same RSS Feeds.

![image](https://user-images.githubusercontent.com/82761116/222911594-5bf9e782-6195-4bbb-897e-ff938bd6b1ad.png)

![image](https://user-images.githubusercontent.com/82761116/222913294-72adbf35-29d8-41e2-be9b-a8a93be8ef70.png)

**Comment by mshibanami** [comment]
Thanks for reporting it, @HelionSmoker.

Now, all the duplicated feeds are removed.

---

For future reference for myself; here is the complete list of duplications:

> XCTAssertEqual failed: ("["jinja", "visual-basic-.net", "zeek", "e-mail", "wikitext", "classic-asp", "unknown"]") is not equal to ("[]")
https://github.com/mshibanami/GitHubTrendingRSS/actions/runs/8769414521/job/24064870245#step:3:265

All of these, except for the Unknown Languages, are also duplicated on GitHub Trending. I added a code to remove all the duplications.
