### ISSUE TITLE
RSS entry per day/week/month instead of entry per repo

### ISSUE THREAD

**Issue by thallada** [mshibanami/GitHubTrendingRSS#16]
Hi, thanks for creating these feeds. I've found a lot of use for them!

I was wondering if it was possible to create alternative feeds that generated an entry per day/week/month and kept a history of the last 10 or so days/weeks/months. I would find it much easier to consume these feeds once every week in one entry instead of flooding my feed reader with a bunch of entries every week.

For example, this is how the github-trending-repos repo works. If you subscribe to an issue you get one email notification per week with a list of repos instead of 10 separate emails: https://github.com/vitalets/github-trending-repos

**Comment by mshibanami** [comment]
Hey @thallada, the original GitHub Trending is also updated every day no matter whether it's weekly or monthly, which makes sense for those who don't want to miss the repositories that are only popular at the beginning and the end of the period of weeks.

By the way, as you may read the README.md, you can host your own feed easily. If you want what you want, I suggest you fork this repository, change [this line](https://github.com/mshibanami/GitHubTrendingRSS/blob/master/.github/workflows/generate_feeds.yml#L5) to `0 0 * * 0` or something, and enjoy your own feed.

**Comment by mshibanami** [comment]
Hi @thallada, the original GitHub Trending is also updated daily, no matter whether it's weekly or monthly, which makes sense for those who don't want to miss the repositories that gain popularity only at the beginning or end of a given time frame.

By the way, as mentioned in the README.md, you can host your own feed easily. If you want what you want, I suggest you fork this repository, change [this line](https://github.com/mshibanami/GitHubTrendingRSS/blob/master/.github/workflows/generate_feeds.yml#L5) to `0 0 * * 0` or something, and enjoy your own feed.
