### ISSUE TITLE
Repo Description in RSS Feed

### ISSUE THREAD

**Issue by alexshadley** [mshibanami/GitHubTrendingRSS#5]
Right now there doesn't seem to be any way to access the description of a repo in the RSS feed. I wonder if the description field, which right now mirrors content, could be used for this?

Awesome project by the way, thanks for making it!

**Comment by mshibanami** [comment]
Hi @alexshadley, Sorry for the late reply and thanks for your feedback.
"Repo Description" you mentioned is this?:

![screenshot](https://user-images.githubusercontent.com/1333214/80907636-f595d880-8d5b-11ea-9780-eba1946097c1.jpg)

**Comment by alexshadley** [comment]
Yes, exactly!

**Comment by mshibanami** [comment]
Ok, I'll have a look at this weekend.

**Comment by mshibanami** [comment]
I already addressed this. Enjoy.
